# Generated by Django 3.2.7 on 2022-12-08 00:31

import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import realestate.utils.media


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=6)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveSmallIntegerField(default=0)),
                ('bedrooms', models.PositiveSmallIntegerField(default=0)),
                ('bathrooms', models.PositiveSmallIntegerField(default=0)),
                ('garage', models.PositiveSmallIntegerField(default=0)),
                ('sqft', models.PositiveSmallIntegerField(default=0)),
                ('lot_size', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pubished', 'Pubished')], default='pending', max_length=50)),
                ('photo_main', models.ImageField(blank=True, null=True, upload_to=realestate.utils.media.get_image_upload_path, verbose_name='Featured Listing Picture')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to=realestate.utils.media.get_image_upload_path, verbose_name='Profile Picture')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to=realestate.utils.media.get_image_upload_path, verbose_name='Profile Picture')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to=realestate.utils.media.get_image_upload_path, verbose_name='Profile Picture')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to=realestate.utils.media.get_image_upload_path, verbose_name='Profile Picture')),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to=realestate.utils.media.get_image_upload_path, verbose_name='Profile Picture')),
                ('photo_6', models.ImageField(blank=True, null=True, upload_to=realestate.utils.media.get_image_upload_path, verbose_name='Profile Picture')),
                ('realtor', auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.realtor')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
