# Generated by Django 3.2.7 on 2022-12-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20221208_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
