# Generated by Django 3.2.7 on 2022-12-08 01:30

from django.db import migrations, models
import realestate.utils.media


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_listing_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to=realestate.utils.media.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to=realestate.utils.media.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to=realestate.utils.media.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to=realestate.utils.media.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to=realestate.utils.media.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_6',
            field=models.ImageField(blank=True, null=True, upload_to=realestate.utils.media.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pubished', 'Published')], default='pending', max_length=50),
        ),
    ]
