from django.db import models


class Gender(models.TextChoices):
    Male = ("male", "Male")
    Female = ("female", "Female")
    Other = ("other", "Other")


class ListingStatus(models.TextChoices):
    Pending = ("pending", "Pending")
    Published = ("pubished", "Published")

class BedRoomChoices(models.TextChoices):
    One = ('1', '1')
    Two = ('2', '2')
    Three = ('3', '3')
    Four = ('4', '4')
    Five = ('5', '5')
    Six = ('6', '6')
    Seven = ('7', '7')
    Eight = ('8', '8')
    Nine = ('9', '9')
    Ten = ('10', '10')

class PriceChoices(models.TextChoices):
    Price1 = ('100000', '$100,000')
    Price2 = ('200000', '$200,000')
    Price3 = ('300000', '$300,000')
    Price4 = ('400000', '$400,000')
    Price5 = ('500000', '$500,000')
    Price6 = ('600000', '$600,000')
    Price7 = ('700000', '$700,000')
    Price8 = ('800000', '$800,000')
    Price9 = ('900000', '$900,000')
    Price10 = ('1000000', '$1M+')


class StateChoices(models.TextChoices):
    Alabama = ("AL", "Alabama")
    Alaska = ("AK", "Alaska")
    Arizona = ("AZ", "Arizona")
    Arkansas = ("AR", "Arkansas")
    California = ("CA", "California")
    Colorado = ("CO", "Colorado")
    Connecticut = ("CT", "Connecticut")
    Delaware = ("DE", "Delaware")
    DistrictOfColumbia = ("DC", "District Of Columbia")
    Florida = ("FL", "Florida")
    Georgia = ("GA", "Georgia")
    Hawaii = ("HI", "Hawaii")
    Idaho = ("ID", "Idaho")
    Illinois = ("IL", "Illinois")
    Indiana = ("IN", "Indiana")
    Iowa = ("IA", "Iowa")
    Kansas = ("KS", "Kansas")
    Kentucky = ("KY", "Kentucky")
    Louisiana = ("LA", "Louisiana")
    Maine = ("ME", "Maine")
    Maryland = ("MD", "Maryland")
    Massachusetts = ("MA", "Massachusetts")
    Michigan = ("MI", "Michigan")
    Minnesota = ("MN", "Minnesota")
    Mississippi = ("MS", "Mississippi")
    Missouri = ("MO", "Missouri")
    Montana = ("MT", "Montana")
    Nebraska = ("NE", "Nebraska")
    Nevada = ("NV", "Nevada")
    NewHampshire = ("NH", "New Hampshire")
    NewJersey = ("NJ", "New Jersey")
    NewMexico = ("NM", "New Mexico")
    NewYork = ("NY", "New York")
    NorthCarolina = ("NC", "North Carolina")
    NorthDakota = ("ND", "North Dakota")
    Ohio = ("OH", "Ohio")
    Oklahoma = ("OK", "Oklahoma")
    Oregon = ("OR", "Oregon")
    Pennsylvania = ("PA", "Pennsylvania")
    RhodeIsland = ("RI", "Rhode Island")
    SouthCarolina = ("SC", "South Carolina")
    SouthDakota = ("SD", "South Dakota")
    Tennessee = ("TN", "Tennessee")
    Texas = ("TX", "Texas")
    Utah = ("UT", "Utah")
    Vermont = ("VT", "Vermont")
    Virginia = ("VA", "Virginia")
    Washington = ("WA", "Washington")
    WestVirginia = ("WV", "West Virginia")
    Wisconsin = ("WI", "Wisconsin")
    Wyoming = ("WY", "Wyoming")
    
