# Generated by Django 3.2.7 on 2022-12-08 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='hire_date',
        ),
    ]
